### ISSUE TITLE
Cannot read properties of undefined (reading runs)

### ISSUE THREAD

**Issue by tleylan** [damonwonghv/youtube-search-api#24]
I only just heard about this library and I don't quite understand the usage. I see GetListByKeyword and it returns a list based upon the key word (obviously). I am more interested in a particular video however. So I tried to call: youtubesearchapi.GetVideoDetails(<video ID>) assuming that the ID was the Youtube video ID.

Trying several different IDs (that exist) has resulted in the following error. Looking at the library code I can see it is trying to access runs but clearly it didn't find a matching object. I don't know if any existing Video ID will work or if it has to be part of playlist, channel or some such.

Would someone clarify this please? Thanks.

TypeError: Cannot read properties of undefined (reading 'runs')
    at Object.GetVideoDetails (D:\Repos\tube-api\node_modules\youtube-search-api\index.js:273:46)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async D:\Repos\tube-api\src\app.ts:178:22

**Comment by jackkingham-au** [comment]
Can also confirm I'm getting the same error, using .GetVideoDetails(<videoId>). Any help would be appreciated 🙂.

**Comment by damonwonghv** [comment]
Can you guys provide the Id you tested before?

**Comment by damonwonghv** [comment]
I tested some videos on youtube, it did not prompt any error. Please provide me with the Video ID.

**Comment by Finalet** [comment]
I am also getting an error on some video IDs when calling `.GetVideoDetails()`. Specifically, this ID `wiH2oJu1XZY`.

Error:
```javascript
TypeError: Cannot read properties of undefined (reading 'twoColumnWatchNextResults')
    at Object.GetVideoDetails ({my_project}\node_modules\youtube-search-api\index.js:259:49)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by developerTested** [comment]
I'm also getting same error when on `initdata.contents.twoColumnWatchNextResults` it occurred if same request sent again.
